---

image: "quay.io/luzifer/repo-runner-image"
checkout_dir: /go/src/github.com/Luzifer/mondash

commands:
  - make publish

environment:
  CGO_ENABLED: 0
  PACKAGES: github.com/Luzifer/mondash github.com/Luzifer/mondash/cmd/mondash-nagios
